---
title: "Mezher"
author: "Ghina Mezher"
format: html
---

Github repository: https://github.com/GhinaMezher/galatic_systems.git

#Dowloading the needed libraries for our lab
```{r}
#| message: false
here::i_am("galatic_systems.Rproj")
library(here)
library(dplyr)
library(ggplot2)
library(tidyr)
library(vroom)
library(knitr)
```

# Question 3
```{r}
allsystems<-vroom(here("data","allsystems.csv"),delim=":",locale=locale(decimal_mark ="."))
allsystems|>summarise("Data set name"="allsystems.csv" ,
                      "Number of star systems"=n(),
                      "Number of variables"=ncol(allsystems),
                      "Are all numerical?"=all(sapply(allsystems,is.numeric)))|>
  knitr::kable()
```

# Question 4
```{r}
allsystems_pivot<-sapply(allsystems,as.character)
allsystems_pivot<-pivot_longer(allsystems_pivot,cols=-c(star_idx,Star_name),names_to="Variable",values_to="Values")
allsystems|>
  summarise("nb of observations"=n(),
  "number of variables"=ncol(allsystems),
  "missing values"=colSums(is.na(allsystems_pivot)),
  "missing observations"=rowSums(is.na(allsystems_pivot)))
```
## Question 5
```{r warning=FALSE}
allsystems|>
  ggplot(aes(x=`star temperature`,y=`Relative Luminosity`))+
  geom_line()+
  geom_rug(alpha=0.1, linewidth=1)+
  labs(x = "Star Temperature", y = "Star Luminosity", title = "Star luminosity according to its temperature")
```
# Question 6
## For the distance
```{r}
max_dist<-allsystems|>select(Star_name,DISTANCE)|>
    slice_max(order_by=DISTANCE)
min_dist<-allsystems|>select(Star_name,DISTANCE)|>
    slice_min(order_by=DISTANCE)

values<-bind_rows(max_dist,min_dist)
bind_cols("Extremes"=c("Maximum","Minimum"),values)
```
## For the temperature
```{r}
max_temp<-allsystems|>select(Star_name,`star temperature`)|>
    slice_max(order_by=`star temperature`,n=1)
min_temp<-allsystems|>select(Star_name,`star temperature`)|>
    slice_min(order_by=`star temperature`,n=1)

values<-bind_rows(max_temp,min_temp)
bind_cols("Extremes"=c("Maximum","Minimum"),values)
```
## For the relative mass
```{r}
max_mass<-allsystems|>select(Star_name,`RELATIVE MASS`)|>
    slice_max(order_by=`RELATIVE MASS`,n=1)
min_mass<-allsystems|>select(Star_name,`RELATIVE MASS`)|>
    slice_min(order_by=`RELATIVE MASS`,n=1)

values<-bind_rows(max_mass,min_mass)
bind_cols("Extremes"=c("Maximum","Minimum"),values)
```
##For the star radius
```{r}
max_rad<-allsystems|>select(Star_name,`Star Radius`)|>
    slice_max(order_by=`Star Radius`,n=1)
min_rad<-allsystems|>select(Star_name,`Star Radius`)|>
    slice_min(order_by=`Star Radius`,n=1)

values<-bind_rows(max_rad,min_rad)
bind_cols("Extremes"=c("Maximum","Minimum"),values)
```

##For the relative luminosity
```{r}
max_lum<-allsystems|>select(Star_name,`Relative Luminosity`)|>
    slice_max(order_by=`Relative Luminosity`,n=1)
min_lum<-allsystems|>select(Star_name,`Relative Luminosity`)|>
    slice_min(order_by=`Relative Luminosity`,n=1)

values<-bind_rows(max_lum,min_lum)
bind_cols("Extremes"=c("Maximum","Minimum"),values)
```


# Question 8
```{r message=FALSE}
BT_FACTIONS<-vroom(here("data","BT%FACTIONS.csv"))
Bt_faction_system<-vroom(here("data","Bt_faction_system.csv"),delim=":")
```
# Question 9
```{r}
Bt_faction_system|>
  filter(FKEY %in% c("A","I","U"))|>
  group_by(FKEY)|>
  summarise(count=n())
```
# Question 10
```{r}
tot_systems<-unique(BT_FACTIONS$FKEY)
included_systems<-unique(Bt_faction_system$FKEY)

not_included_systems<-tot_systems[!(tot_systems%in%included_systems)]

print(length(not_included_systems))

```
#Question 11
```{r}
merged_systems<-merge(Bt_faction_system,BT_FACTIONS,by="FKEY")
merged_systems|>group_by(`Name Of The Faction`)|>
  summarise(count=n())|>
  filter(count>0)|>
  ggplot(aes(x=`Name Of The Faction`,y=count))+
  geom_bar(stat="identity",fill="skyblue")+
  theme(axis.text.x=element_text(angle=90,hjust=1))+
  labs(x="Faction Name",y="Number of Star systems",title="Number of star systems per faction")
```

#Question 12
```{r}
merge_allsystems<-merge(allsystems,Bt_faction_system,by="star_idx")
merge_allsystems|>filter(FKEY!="A" & FKEY!="I"& FKEY!="U")|>
  ggplot(aes(x=FKEY,y=DISTANCE))+
  geom_boxplot()+
  theme(axis.text.x=element_text(angle=90,hjust=1))+
  labs(x="faction key",y="Distance from the Sun",title="Distance from the Sun according to system factions")
  
```
#Question 13
```{r}
merge_allsystems|>
  filter(FKEY!="A" & FKEY!="I"& FKEY!="U")|>
  group_by(FKEY)|>

```



